apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cnvos-acf
resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
images:
  - name: cnvos-acf
    newName: rg.fr-par.scw.cloud/djnd/cnvos-acf
    newTag: '4adf8a159739864bdb97e4c7e7f859948b72c961'
