# Generated by Django 4.2.16 on 2024-09-23 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_projecttype_options_projectpage_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectpage",
            name="project_value",
        ),
    ]
