# Generated by Django 4.2.16 on 2024-09-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_genericsocialmediasettings_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenericSocialMediaSettings',
            new_name='FinancerSettings',
        ),
        migrations.AlterModelOptions(
            name='financersettings',
            options={'verbose_name': 'Financer'},
        ),
    ]
