# Generated by Django 4.2.16 on 2024-09-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_rename_genericsocialmediasettings_financersettings_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FinancerSettings",
            new_name="GeneralSettings",
        ),
    ]
